# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hackaton Extia 2019' do
  pod 'VerticalCardSwiper', '~> 2.0'
  pod 'Alamofire', '~> 4.4'
  use_frameworks!

  # Pods for Hackaton Extia 2019

end
